### ISSUE TITLE
visual encoder

### ISSUE THREAD

**Issue by miumiuc** [X-PLUG/Youku-mPLUG#20]
请问一下，论文中写的是将TimeSformer作为视觉编码器，但是代码中用的是clip_vit_b16.pth？clip的预训练权重能加载到TimeSformer上吗？

**Comment by auhowielau** [comment]
是的，视觉编码器采用TimeSformer结构，利用clip_vit_b16初始化部分参数（与时序建模无关的参数）

**Comment by zhiweibi** [comment]
请问这个文件在哪里下载呢

**Comment by RuixiangZhao** [comment]
@zhiweibi 请问你找到了吗？
