### ISSUE TITLE
The evaluation results as well as leaderboards look very different

### ISSUE THREAD

**Issue by zhimin-z** [X-PLUG/Youku-mPLUG#23]
The original Arxiv [paper](https://arxiv.org/abs/2306.04362):
![image](https://github.com/X-PLUG/Youku-mPLUG/assets/8592144/12ad96ce-d26d-48ff-acaa-32b7b8ba9c9e)
The GitHub [Readme](https://github.com/X-PLUG/Youku-mPLUG/blob/9d3dd3f41570d0e5dae32b6536757c6544b53121/README.md?plain=1#L104):
![image](https://github.com/X-PLUG/Youku-mPLUG/assets/8592144/74c5aa5e-c3b1-43fb-a7f1-b89b829b1540)

**Comment by auhowielau** [comment]
The paper shows the results on the **test sets**. Since the test set data hasn't been released, we provide the results on the **validation sets** for reference in Readme.

**Comment by zhimin-z** [comment]
> The paper shows the results on the **test sets**. Since the test set data hasn't been released, we provide the results on the **validation sets** for reference in Readme.

This should be clarified in the documentation, thanks!
