### ISSUE TITLE
Is there a progress bar when downloading?

### ISSUE THREAD

**Issue by Mashiro009** [X-PLUG/Youku-mPLUG#5]
Thank you for your great contribution to the video/text pre-training field and community.

I'm trying to download the data using my own sdk_token following the official code, but nothing shows up on the command line when running the "MsDataset.load", so I'm not sure if it's downloading properly and how long it will take for the download to complete. Is there a download progress bar?

**Comment by MAGAer13** [comment]
The modelscope team are working on it. Stay tuned.
